version: "3"

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dentall
    ports:
      - "3306:3306"
    volumes:
      - ./DockerData/DentAll/mysql_data:/var/lib/mysql